package brain

const AXON_PROB_SPHERE = 4.0
const FIRING_THRESHOLD = 1.0
const CONN_WEIGHT_INCREASE = 0.05
const CONN_WEIGHT_DECREASE = 0.05
const CONN_WEIGHT_DECAY = 0.02
const MAX_CONN_WEIGHT = 2.25
const MIN_CONN_WEIGHT = 0.25
const DYNAMIC_SYNAPSE_PROB_SPHERE = 2.0
const SYNAPSE_PROB_SPHERE = 1.5
const INVERSE_INHIBITORY_PROB = 5
const INITIAL_SYNAPSE_COUNT = 3

const NUMBER_OF_CENTERS = 3
const CENTER_RADIUS = 3.0
const CENTER_VECTOR_FACTOR = 2.0

const PROB_INITIAL_ON = 0.25

const FIRING_RATE_INCREASE = 0.2
const FIRING_RATE_DECREASE = 0.5
const FIRING_RATE_MIN = 1.0

var MIN_CONNECTIONS = 10
var MAX_CONNECTIONS = 15
var SYNAPSE_LEARNING_RATE = 1.0